ix86: Fix build failure when !CONFIG_X86_IO_APIC
mp_should_keep_irq() isn't really IO-APIC related, and
considering that it's being used solely in arch/x86/pci/ likely
both declaration and definition got misplaced even without
considering the resulting build failure:

  .../arch/x86/pci/irq.c: In function ‘pirq_disable_irq’:
  .../arch/x86/pci/irq.c:1259: error: implicit declaration of function ‘mp_should_keep_irq’
  make[3]: *** [arch/x86/pci/irq.o] Error 1

Move them to better places.

Signed-off-by: Jan Beulich <jbeulich@suse.com>
Cc: Jiang Liu <jiang.liu@linux.intel.com>
Link: http://lkml.kernel.org/r/54184CC802000078000355EE@mail.emea.novell.com
Signed-off-by: Ingo Molnar <mingo@kernel.org>